### ISSUE TITLE
hey how do i join the proxathon

### ISSUE THREAD

**Issue by Coding4Hours** [NightProxy/Daylight#2]
i want to join

**Comment by not-amplify** [comment]
> i want to join

Proxathon entries are no longer being accepted, however you can join our proxathon in a few months(if we still decide to have one)

**Comment by Coding4Hours** [comment]
if they are being accepted how do i join

**Comment by not-amplify** [comment]
> if they are being accepted how do i join

Join TN, code a proxy that fits the theme once its announced, and submit by a month later.
